environment:
  nodejs_version: "6.5.0"

os: unstable

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install nsis -pre -y
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
